Lost Bunny: Journey Home: resourcemanager::ResourceManager Class Reference
resourcemanager::ResourceManager Class Reference
Data Structures
struct SoundData
Public Member Functions
this (SDL_Renderer *r)
SDL_Texture * loadTexture (string path)
SDL_Texture * getTexture (string name)
string getAnimationPath (string name)
string getTilemapPath (string name)
void unloadAll ()
void loadFromJSON (string path="./resources.json")
void loadSound (string path)
void playSound (string name)
Detailed Description
Definition at line 10 of file resourcemanager.d.
Constructor & Destructor Documentation
this()
resourcemanager::ResourceManager::this (SDL_Renderer * r) inline
Definition at line 26 of file resourcemanager.d.
{
        renderer = r;
    }
Member Function Documentation
getAnimationPath()
string resourcemanager::ResourceManager::getAnimationPath (string name) inline
Definition at line 68 of file resourcemanager.d.
{
        if (name in animationPaths)
            return animationPaths[name];
        else
            throw new Exception("Animation not found: " ~ name);
    }
getTexture()
SDL_Texture * resourcemanager::ResourceManager::getTexture (string name) inline
Definition at line 55 of file resourcemanager.d.
{
        if (name in texturePaths) {
            string texPath = texturePaths[name];
            if (!(texPath in textures))
                return loadTexture(texPath);
            return textures[texPath];
        }
        if (!(name in textures))
            return loadTexture(name);
        return textures[name];
    }
References loadTexture().
getTilemapPath()
string resourcemanager::ResourceManager::getTilemapPath (string name) inline
Definition at line 75 of file resourcemanager.d.
{
        if (name in tilemapPaths)
            return tilemapPaths[name];
        else
            throw new Exception("Tilemap not found: " ~ name);
    }
loadFromJSON()
void resourcemanager::ResourceManager::loadFromJSON (string path = "./resources.json") inline
Definition at line 93 of file resourcemanager.d.
{
        if (!exists(path)) {
            writeln("Warning: resources.json not found at ", path);
            return;
        }
        auto jsonData = readText(path).parseJSON();
        if ("textures" in jsonData) {
            auto texList = jsonData["textures"].array;
            foreach (t; texList) {
                string texPath = t.str;
                string name = texPath.baseName.stripExtension;
                texturePaths[name] = texPath;
                loadTexture(texPath);
            }
        }
        if ("animations" in jsonData) {
            auto animList = jsonData["animations"].array;
            foreach (a; animList) {
                string animPath = a.str;
                string name = animPath.baseName.stripExtension;
                animationPaths[name] = animPath;
            }
        }
        if ("sounds" in jsonData) {
            auto sndList = jsonData["sounds"].array;
            foreach (s; sndList) {
                string sndPath = s.str;
                string name = sndPath.baseName.stripExtension;
                soundPaths[name] = sndPath;
            }
        }
        if ("tilemaps" in jsonData) {
            auto tmList = jsonData["tilemaps"].array;
            foreach (tm; tmList) {
                string tmPath = tm.str;
                string name = tmPath.baseName.stripExtension;
                tilemapPaths[name] = tmPath;
            }
        }
    }
References loadTexture().
loadSound()
void resourcemanager::ResourceManager::loadSound (string path) inline
Definition at line 139 of file resourcemanager.d.
{
        if (path in sounds) return;
        SDL_AudioSpec spec;
        ubyte* buf = null;
        uint len = 0;
        auto res = SDL_LoadWAV(path.toStringz, &spec, &buf, &len);
        if (buf is null) {
            writeln("Failed to load WAV: ", path);
            return;
        }
        SoundData sd;
        sd.spec = spec;
        sd.buffer = buf;
        sd.length = len;
        sounds[path] = sd;
    }
References resourcemanager::ResourceManager::SoundData::buffer, resourcemanager::ResourceManager::SoundData::length, and resourcemanager::ResourceManager::SoundData::spec.
Referenced by playSound().
loadTexture()
SDL_Texture * resourcemanager::ResourceManager::loadTexture (string path) inline
Definition at line 30 of file resourcemanager.d.
{
        if (path in textures) return textures[path];
        auto surface = SDL_LoadBMP(path.toStringz);
        if (surface is null) {
            writeln("✗ ERROR: Failed to load surface: ", path);
            writeln("  SDL Error: ", SDL_GetError().fromStringz);
            return null;
        }
        auto texture = SDL_CreateTextureFromSurface(renderer, surface);
        SDL_DestroySurface(surface);
        if (texture is null) {
            writeln("✗ ERROR: Failed to create texture from surface: ", path);
            writeln("  SDL Error: ", SDL_GetError().fromStringz);
            return null;
        }
        textures[path] = texture;
        writeln("✓ Loaded texture: ", path);
        return texture;
    }
Referenced by getTexture(), and loadFromJSON().
playSound()
void resourcemanager::ResourceManager::playSound (string name) inline
Definition at line 156 of file resourcemanager.d.
{
        if (!(name in soundPaths)) return;
        string path = soundPaths[name];
        if (!(path in sounds)) loadSound(path);
        auto sd = sounds[path];
        if (sd.buffer is null) return;
        if (audioStream is null) {
            audioStream = SDL_OpenAudioDeviceStream(SDL_AudioDevice.defaultPlayback, &sd.spec, null, null);
            if (audioStream is null) {
                writeln("Failed to open audio device stream");
                return;
            }
        }
        SDL_PutAudioStreamData(audioStream, sd.buffer, cast(int) sd.length);
        SDL_ResumeAudioStreamDevice(audioStream);
    }
References loadSound().
unloadAll()
void resourcemanager::ResourceManager::unloadAll () inline
Definition at line 82 of file resourcemanager.d.
                     {
        foreach (t; textures.byValue)
            if (t !is null) SDL_DestroyTexture(t);
        textures.clear();
        foreach(sd; sounds.byValue) {
            if (sd.buffer !is null) SDL_free(sd.buffer);
        }
        sounds.clear();
        if (audioStream !is null) SDL_DestroyAudioStream(audioStream);
    }
The documentation for this class was generated from the following file:
source/resourcemanager.d