Lost Bunny: Journey Home: component_system::GameObject Class Reference
component_system::GameObject Class Reference
Public Member Functions
this (string name)
void AddComponent (ComponentType type, IComponent comp)
T GetComponent T (ComponentType type)
void AddScript (ScriptComponent s)
T GetScript T ()
void Update ()
void Render (SDL_Renderer *renderer, Camera camera=null)
SDL_FRect * TransformRect ()
Data Fields
string name
IComponent[] mComponents
ScriptComponent[] mScripts
Detailed Description
Definition at line 150 of file component_system.d.
Constructor & Destructor Documentation
this()
component_system::GameObject::this (string name) inline
Definition at line 155 of file component_system.d.
                     {
        this.name = name;
        mComponents = new IComponent[cast(size_t) ComponentType.SCRIPT + 1];
    }
References mComponents, and name.
Member Function Documentation
AddComponent()
void component_system::GameObject::AddComponent (ComponentType type, IComponent comp) inline
Definition at line 160 of file component_system.d.
{ mComponents[cast(size_t)type] = comp; }
References mComponents.
AddScript()
void component_system::GameObject::AddScript (ScriptComponent s) inline
Definition at line 168 of file component_system.d.
{ s.owner = this; mScripts ~= s; }
References mScripts, and component_system::ScriptComponent::owner.
Render()
void component_system::GameObject::Render (SDL_Renderer * renderer, Camera camera = null) inline
Definition at line 185 of file component_system.d.
{
        auto tex  = cast(TextureComponent) (cast(size_t)ComponentType.TEXTURE < mComponents.length ? mComponents[cast(size_t)ComponentType.TEXTURE] : null);
        auto xf   = cast(TransformComponent) (cast(size_t)ComponentType.TRANSFORM < mComponents.length ? mComponents[cast(size_t)ComponentType.TRANSFORM] : null);
        auto anim = cast(AnimationComponent) (cast(size_t)ComponentType.ANIMATION < mComponents.length ? mComponents[cast(size_t)ComponentType.ANIMATION] : null);
        if (tex !is null && xf !is null){
            SDL_FRect renderRect = xf.rect;
            if (camera !is null) {
                if (!camera.isVisible(xf.rect)) {
                    return;
                }
                renderRect = camera.worldToScreen(xf.rect);
            }
            tex.Render(renderer, &renderRect, anim is null ? null : &anim.src, xf.rotation);
        }
    }
References mComponents.
T() [1/2]
T GetScript component_system::GameObject::T () inline
Definition at line 170 of file component_system.d.
                     {
        foreach (s; mScripts) {
            auto casted = cast(T) s;
            if (casted !is null) return casted;
        }
        return null;
    }
References mScripts, and T().
T() [2/2]
T GetComponent component_system::GameObject::T (ComponentType type) inline
Definition at line 162 of file component_system.d.
{
        auto ic = (cast(size_t)type < mComponents.length) ? mComponents[cast(size_t)type] : null;
        if (ic is null) return null;
        return cast(T) ic;
    }
References mComponents, and T().
Referenced by T(), and T().
TransformRect()
SDL_FRect * component_system::GameObject::TransformRect () inline
Definition at line 203 of file component_system.d.
{
        auto ic = (cast(size_t)ComponentType.TRANSFORM < mComponents.length) ? mComponents[cast(size_t)ComponentType.TRANSFORM] : null;
        auto xf = cast(TransformComponent) ic;
        return xf is null ? null : &xf.rect;
    }
References mComponents.
Referenced by component_system::AnimationComponent::Update().
Update()
void component_system::GameObject::Update () inline
Definition at line 178 of file component_system.d.
                 { // update components then scripts
        foreach(i, comp; mComponents) {
            if (comp !is null) comp.Update(this);
        }
        foreach(script; mScripts){ script.OnUpdate(this); }
    }
References mComponents, and mScripts.
Field Documentation
mComponents
IComponent [] component_system::GameObject::mComponents
Definition at line 152 of file component_system.d.
Referenced by AddComponent(), Render(), T(), this(), TransformRect(), and Update().
mScripts
ScriptComponent [] component_system::GameObject::mScripts
Definition at line 153 of file component_system.d.
Referenced by AddScript(), T(), and Update().
name
string component_system::GameObject::name
Definition at line 151 of file component_system.d.
Referenced by this().
The documentation for this class was generated from the following file:
source/component_system.d