Lost Bunny: Journey Home: lostbunnyscene Namespace Reference
lostbunnyscene Namespace Reference
Functions
writeln ("Initializing Lost Bunny Scene - Level ", levelNumber, "...")
sceneTree. clear ()
if (tilemap is null)
createBlobs ()
writeln ("=== LOADING BUNNY FRAMES ===")
if (frame1 !is null) bunnyFrames ~
if (frame2 !is null) bunnyFrames ~
if (frame3 !is null) bunnyFrames ~
if (frame4 !is null) bunnyFrames ~
writeln ("✓ Loaded ", bunnyFrames.length, " bunny animation frames")
if (bunnySittingTexture !is null)
if (bunnyFrames.length==0)
if (bunnyFrames.length > 0)
player. AddComponent (ComponentType.TRANSFORM, transform)
addGameObject (player, "Player")
writeln ("Level ", levelNumber, " initialized!")
override void cleanup ()
override void handleInput (SDL_Event event)
override void update ()
override void render (SDL_Renderer *renderer)
Variables
graceTimer = 1.0f
carrotsCollected = 0
playerX = 60
playerY = 350
velocityY = 0.0f
velocityX = 0.0f
isOnGround = false
isTouchingWallLeft = false
isTouchingWallRight = false
platforms. length = 0
tileTexture = resourceManager.getTexture("tile")
boneTexture = resourceManager.getTexture("bone")
skullTexture = resourceManager.getTexture("skull")
spikeTexture = resourceManager.getTexture("spikes")
blobTexture = resourceManager.getTexture("blob")
carrotTexture = resourceManager.getTexture("carrot")
backgroundTexture = resourceManager.getTexture("background")
tilemap = TilemapLevel.loadFromFile(tilemapFile)
else
auto frame1 = resourceManager.getTexture("bunny_frame1")
auto frame2 = resourceManager.getTexture("bunny_frame2")
auto frame3 = resourceManager.getTexture("bunny_frame3")
auto frame4 = resourceManager.getTexture("bunny_frame4")
bunnySittingTexture = resourceManager.getTexture("bunny_sitting")
player = new GameObject("Player")
auto transform = new TransformComponent(playerX, playerY, PLAYER_WIDTH, PLAYER_HEIGHT)
Function Documentation
AddComponent()
player. lostbunnyscene::AddComponent (ComponentType. TRANSFORM, transform)
References player, and transform.
addGameObject()
lostbunnyscene::addGameObject (player , "Player")
References addGameObject(), and player.
Referenced by addGameObject().
cleanup()
override void lostbunnyscene::cleanup ()
Definition at line 217 of file lostbunnyscene.d.
{
        writeln("Cleaning up Lost Bunny Scene...");
    }
References cleanup(), and writeln().
Referenced by cleanup().
clear()
sceneTree. lostbunnyscene::clear ()
createBlobs()
void lostbunnyscene::createBlobs ()
Definition at line 703 of file lostbunnyscene.d.
{
        import std.random;
        auto rnd = Random(unpredictableSeed);
        // int blobCount = uniform(3, 6, rnd);
        int blobCount = 2;
        foreach (i; 0 .. blobCount) {
            Blob blob;
            bool validPosition = false;
            int attempts = 0;
            while (!validPosition && attempts < 50) {
                blob.rect.x = uniform(50.0f, 550.0f, rnd);
                blob.rect.y = uniform(50.0f, 350.0f, rnd);
                float dx = blob.rect.x - 60.0f;
                float dy = blob.rect.y - 350.0f;
                float distSq = dx*dx + dy*dy;
                if (distSq > 150.0f * 150.0f) {
                    validPosition = true;
                }
                attempts++;
            }
            // Create blobs in different sizes
            int sizeCategory = uniform(0, 3, rnd);
            float size;
            if (sizeCategory == 0) {
                size = uniform(30.0f, 45.0f, rnd); // Small
            } else if (sizeCategory == 1) {
                size = uniform(40.0f, 60.0f, rnd); // Medium
            } else {
                size = uniform(60.0f, 80.0f, rnd); // Large
            }
            blob.rect.w = size;
            blob.rect.h = size;
            blob.speed = uniform(40.0f, 80.0f, rnd);
            // Random direction
            float angle = uniform(0.0f, 6.28f, rnd);
            blob.velocityX = cos(angle) * blob.speed;
            blob.velocityY = sin(angle) * blob.speed;
            blobs ~= blob;
        }
        writeln("✓ Created ", blobs.length, " blobs");
    }
References createBlobs(), and writeln().
Referenced by createBlobs().
handleInput()
override void lostbunnyscene::handleInput (SDL_Event event)
Definition at line 221 of file lostbunnyscene.d.
{
        if (event.type == SDL_EVENT_KEY_DOWN) {
            auto sc = event.key.scancode;
            // ESC to menu
            if (sc == SDL_SCANCODE_ESCAPE && returnToMenuCallback !is null) {
                returnToMenuCallback();
                return;
            }
            // Jump
            if (sc == SDL_SCANCODE_SPACE || sc == SDL_SCANCODE_UP || sc == SDL_SCANCODE_W) {
                if (isOnGround) {
                    // Normal jump
                    velocityY = jumpForce;
                    isOnGround = false;
                } else if (isTouchingWallLeft) {
                    // Wall jump off left wall
                    velocityY = wallJumpForce;
                    playerX += wallJumpHorizontalBoost * 0.1f;
                    facingLeft = false;
                } else if (isTouchingWallRight) {
                    // Wall jump off right wall
                    velocityY = wallJumpForce;
                    playerX -= wallJumpHorizontalBoost * 0.1f;
                    facingLeft = true;
                }
            }
        }
    }
References handleInput(), isOnGround, isTouchingWallLeft, isTouchingWallRight, playerX, and velocityY.
Referenced by handleInput().
if() [1/8]
lostbunnyscene::if (bunnyFrames. length, 0)
Definition at line 204 of file lostbunnyscene.d.
{
            auto playerTexture = new TextureComponent(bunnyFrames[0]);
            player.AddComponent(ComponentType.TEXTURE, playerTexture);
        }
References player.
if() [2/8]
lostbunnyscene::if (bunnyFrames. length = = 0)
Definition at line 198 of file lostbunnyscene.d.
{
            writeln("✗ ERROR: No bunny frames loaded!");
        }
References writeln().
if() [3/8]
lostbunnyscene::if (bunnySittingTexture !is null)
Definition at line 194 of file lostbunnyscene.d.
{
            writeln("✓ Loaded bunny sitting texture");
        }
References bunnySittingTexture, and writeln().
if() [4/8]
lostbunnyscene::if (frame1 !is null)
References frame1.
if() [5/8]
lostbunnyscene::if (frame2 !is null)
References frame2.
if() [6/8]
lostbunnyscene::if (frame3 !is null)
References frame3.
if() [7/8]
lostbunnyscene::if (frame4 !is null)
References frame4.
if() [8/8]
lostbunnyscene::if (tilemap is null)
Definition at line 164 of file lostbunnyscene.d.
{
            writeln("✗ Failed to load tilemap from ", tilemapFile, ", creating default level");
            // Create platforms
            createPlatforms();
            // Create spikes
            createSpikes();
            // Create carrots
            createCarrots();
        } else {
References writeln().
render()
override void lostbunnyscene::render (SDL_Renderer * renderer)
Definition at line 481 of file lostbunnyscene.d.
{
        if (!isActive) return;
        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_RenderClear(renderer);
        if (backgroundTexture !is null) {
            SDL_FRect dst;
            dst.x = 0;
            dst.y = 0;
            dst.w = 640;
            dst.h = 480;
            SDL_RenderTexture(renderer, backgroundTexture, null, &dst);
        }
        // Render platforms
        renderPlatforms(renderer);
        renderDecorTiles(renderer);
        // Render spikes
        renderSpikes(renderer);
        // Render blobs
        renderBlobs(renderer);
        // Render carrots
        renderCarrots(renderer);
        // Render player
        renderPlayer(renderer);
        // Draw carrot counter
        drawCarrotCounter(renderer);
        SDL_RenderPresent(renderer);
    }
References backgroundTexture, and render().
Referenced by render().
update()
override void lostbunnyscene::update ()
Definition at line 252 of file lostbunnyscene.d.
{
        if (!isActive) return;
        const bool* keyState = SDL_GetKeyboardState(null);
        isMoving = false;
        bool hasInput = false;
        float accelX = 0.0f;
        if (keyState[SDL_SCANCODE_LEFT] || keyState[SDL_SCANCODE_A]) {
            accelX -= acceleration;
            facingLeft = true;
            hasInput = true;
        }
        if (keyState[SDL_SCANCODE_RIGHT] || keyState[SDL_SCANCODE_D]) {
            accelX += acceleration;
            facingLeft = false;
            hasInput = true;
        }
        velocityX += accelX * deltaTime;
        if (!hasInput) {
            if (velocityX > 0) {
                velocityX -= friction * deltaTime;
                if (velocityX < 0) velocityX = 0;
            } else if (velocityX < 0) {
                velocityX += friction * deltaTime;
                if (velocityX > 0) velocityX = 0;
            }
        }
        // Clamp max speed
        if (velocityX >  max_run_speed) {
            velocityX =  max_run_speed;
        }
        if (velocityX < -max_run_speed) {
            velocityX = -max_run_speed;
        }
        // Use velocityX to move
        float dx = velocityX * deltaTime;
        // Vertical movement
        velocityY += gravity * deltaTime;
        // Update positions
        playerX += dx;
        playerY += velocityY * deltaTime;
        // Decide if we consider this "moving" for animation
        if (velocityX > move_threshold || velocityX < -move_threshold) {
            isMoving = true;
        }
        // Platform collision
        isOnGround = false;
        isTouchingWallLeft = false;
        isTouchingWallRight = false;
        // Full visual rect (for mapping back)
        SDL_FRect playerRect;
        playerRect.x = playerX;
        playerRect.y = playerY;
        playerRect.w = PLAYER_WIDTH;
        playerRect.h = PLAYER_HEIGHT;
        // collision rect for platforms (shrink horizontal collision)
        SDL_FRect hitboxRect;
        hitboxRect.x = playerX + PLAYER_HITBOX_INSET_X;
        hitboxRect.y = playerY;
        hitboxRect.w = PLAYER_WIDTH - PLAYER_HITBOX_INSET_X * 2;
        hitboxRect.h = PLAYER_HEIGHT;
        foreach (ref platform; platforms) {
            if (SDL_HasRectIntersectionFloat(&hitboxRect, &platform)) {
                float overlapLeft = (hitboxRect.x + hitboxRect.w) - platform.x;
                float overlapRight = (platform.x + platform.w) - hitboxRect.x;
                float overlapTop = (hitboxRect.y + hitboxRect.h) - platform.y;
                float overlapBottom = (platform.y + platform.h) - hitboxRect.y;
                float minOverlap = overlapLeft;
                int direction = 0;
                if (overlapRight < minOverlap) {
                    minOverlap = overlapRight;
                    direction = 1;
                }
                if (overlapTop < minOverlap) {
                    minOverlap = overlapTop;
                    direction = 2;
                }
                if (overlapBottom < minOverlap) {
                    minOverlap = overlapBottom;
                    direction = 3;
                }
                if (direction == 0) {
                    // Colliding with platform from the left (bunny's right side)
                    hitboxRect.x = platform.x - hitboxRect.w;
                    isTouchingWallRight = true;
                    velocityX = 0;
                } else if (direction == 1) {
                    // Colliding from the right (bunny's left side)
                    hitboxRect.x = platform.x + platform.w;
                    velocityX = 0;
                    isTouchingWallLeft = true;
                } else if (direction == 2) {
                    // Landing on top
                    hitboxRect.y = platform.y - hitboxRect.h;
                    velocityY = 0;
                    isOnGround = true;
                } else if (direction == 3) {
                    // Hitting underside
                    hitboxRect.y = platform.y + platform.h;
                    velocityY = 0;
                }
                // Map hitbox back to player position
                playerX = hitboxRect.x - PLAYER_HITBOX_INSET_X;
                playerY = hitboxRect.y;
                // Update rects for any more platforms this frame
                playerRect.x = playerX;
                playerRect.y = playerY;
                hitboxRect.x = playerX + PLAYER_HITBOX_INSET_X;
                hitboxRect.y = playerY;
            }
        }
        // Keep player in horizontal bounds
        playerX = max(0.0f, min(640.0f - PLAYER_WIDTH, playerX));
        if (playerY > 450) {
            writeln("Fell onto spike floor!");
            resetToMenu();
            return;
        }
        // Update blobs
        updateBlobs();
        // Check collisions
        checkCollisions();
        // Check win condition (reached right side of screen)
        if (playerX >= 580) {
            writeln("Victory! You made it to the goal!");
            winLevel();
            return;
        }
        // Update player transform
        if (player !is null) {
            auto transform = player.GetComponent!TransformComponent(ComponentType.TRANSFORM);
            if (transform !is null) {
                transform.rect.x = playerX;
                transform.rect.y = playerY;
            }
        }
        // Update bunny animation
        updateBunnyAnimation();
        // Update grace timer
        if (graceTimer > 0) {
            graceTimer -= deltaTime;
        }
        // Update scene tree
        sceneTree.update();
    }
References graceTimer, isOnGround, isTouchingWallLeft, isTouchingWallRight, player, playerX, playerY, transform, update(), velocityX, velocityY, and writeln().
Referenced by update().
writeln() [1/4]
lostbunnyscene::writeln ("✓ Loaded " , bunnyFrames. length, " bunny animation frames")
References writeln().
writeln() [2/4]
lostbunnyscene::writeln ()
References writeln().
writeln() [3/4]
lostbunnyscene::writeln ("Initializing Lost Bunny Scene - Level " , levelNumber , "...")
References writeln().
Referenced by cleanup(), createBlobs(), if(), if(), if(), update(), writeln(), writeln(), writeln(), and writeln().
writeln() [4/4]
lostbunnyscene::writeln ("Level " , levelNumber , " initialized!")
References writeln().
Variable Documentation
backgroundTexture
lostbunnyscene::backgroundTexture = resourceManager.getTexture("background")
Definition at line 160 of file lostbunnyscene.d.
Referenced by render().
blobTexture
lostbunnyscene::blobTexture = resourceManager.getTexture("blob")
Definition at line 158 of file lostbunnyscene.d.
boneTexture
lostbunnyscene::boneTexture = resourceManager.getTexture("bone")
Definition at line 155 of file lostbunnyscene.d.
bunnySittingTexture
lostbunnyscene::bunnySittingTexture = resourceManager.getTexture("bunny_sitting")
Definition at line 186 of file lostbunnyscene.d.
Referenced by if().
carrotsCollected
lostbunnyscene::carrotsCollected = 0
Definition at line 137 of file lostbunnyscene.d.
carrotTexture
lostbunnyscene::carrotTexture = resourceManager.getTexture("carrot")
Definition at line 159 of file lostbunnyscene.d.
else
lostbunnyscene::else
Initial value:
{
            loadFromTilemap()
Definition at line 172 of file lostbunnyscene.d.
frame1
auto lostbunnyscene::frame1 = resourceManager.getTexture("bunny_frame1")
Definition at line 182 of file lostbunnyscene.d.
Referenced by if().
frame2
auto lostbunnyscene::frame2 = resourceManager.getTexture("bunny_frame2")
Definition at line 183 of file lostbunnyscene.d.
Referenced by if().
frame3
auto lostbunnyscene::frame3 = resourceManager.getTexture("bunny_frame3")
Definition at line 184 of file lostbunnyscene.d.
Referenced by if().
frame4
auto lostbunnyscene::frame4 = resourceManager.getTexture("bunny_frame4")
Definition at line 185 of file lostbunnyscene.d.
Referenced by if().
graceTimer
lostbunnyscene::graceTimer = 1.0f
Definition at line 136 of file lostbunnyscene.d.
Referenced by update().
isOnGround
lostbunnyscene::isOnGround = false
Definition at line 142 of file lostbunnyscene.d.
Referenced by handleInput(), and update().
isTouchingWallLeft
lostbunnyscene::isTouchingWallLeft = false
Definition at line 143 of file lostbunnyscene.d.
Referenced by handleInput(), and update().
isTouchingWallRight
lostbunnyscene::isTouchingWallRight = false
Definition at line 144 of file lostbunnyscene.d.
Referenced by handleInput(), and update().
length
bunnyFrames lostbunnyscene::length = 0
Definition at line 147 of file lostbunnyscene.d.
player
lostbunnyscene::player = new GameObject("Player")
Definition at line 203 of file lostbunnyscene.d.
Referenced by AddComponent(), addGameObject(), if(), and update().
playerX
lostbunnyscene::playerX = 60
Definition at line 138 of file lostbunnyscene.d.
Referenced by handleInput(), and update().
playerY
lostbunnyscene::playerY = 350
Definition at line 139 of file lostbunnyscene.d.
Referenced by update().
skullTexture
lostbunnyscene::skullTexture = resourceManager.getTexture("skull")
Definition at line 156 of file lostbunnyscene.d.
spikeTexture
lostbunnyscene::spikeTexture = resourceManager.getTexture("spikes")
Definition at line 157 of file lostbunnyscene.d.
tilemap
lostbunnyscene::tilemap = TilemapLevel.loadFromFile(tilemapFile)
Definition at line 163 of file lostbunnyscene.d.
tileTexture
lostbunnyscene::tileTexture = resourceManager.getTexture("tile")
Definition at line 154 of file lostbunnyscene.d.
transform
auto lostbunnyscene::transform = new TransformComponent(playerX, playerY, PLAYER_WIDTH, PLAYER_HEIGHT)
Definition at line 209 of file lostbunnyscene.d.
Referenced by AddComponent(), and update().
velocityX
lostbunnyscene::velocityX = 0.0f
Definition at line 141 of file lostbunnyscene.d.
Referenced by update().
velocityY
lostbunnyscene::velocityY = 0.0f
Definition at line 140 of file lostbunnyscene.d.
Referenced by handleInput(), and update().