Lost Bunny: Journey Home: finalscene Namespace Reference
finalscene Namespace Reference
Functions
if (frame1 !is null) bunnyFrames ~
if (frame2 !is null) bunnyFrames ~
if (frame3 !is null) bunnyFrames ~
if (frame4 !is null) bunnyFrames ~
if (bunnyFrames.length > 0)
player. AddComponent (ComponentType.TRANSFORM, transform)
addGameObject (player, "Player")
writeln ("Final Scene initialized!")
override void cleanup ()
override void handleInput (SDL_Event event)
override void update ()
override void render (SDL_Renderer *renderer)
Variables
playerX = 60
playerY = 368
velocityY = 0.0f
isOnGround = true
tileTexture = resourceManager.getTexture("tile")
deadBunnyTexture = resourceManager.getTexture("bunny_dead")
bunnyFrames. length = 0
auto frame1 = resourceManager.getTexture("bunny_frame1")
auto frame2 = resourceManager.getTexture("bunny_frame2")
auto frame3 = resourceManager.getTexture("bunny_frame3")
auto frame4 = resourceManager.getTexture("bunny_frame4")
bunnySittingTexture = resourceManager.getTexture("bunny_sitting")
player = new GameObject("Player")
auto transform = new TransformComponent(playerX, playerY, 48, 48)
Function Documentation
AddComponent()
player. finalscene::AddComponent (ComponentType. TRANSFORM, transform)
References player, and transform.
addGameObject()
finalscene::addGameObject (player , "Player")
References addGameObject(), and player.
Referenced by addGameObject().
cleanup()
override void finalscene::cleanup ()
Definition at line 101 of file finalscene.d.
{
        writeln("Cleaning up Final Scene...");
    }
References cleanup(), and writeln().
Referenced by cleanup().
handleInput()
override void finalscene::handleInput (SDL_Event event)
Definition at line 105 of file finalscene.d.
{
        if (event.type == SDL_EVENT_KEY_DOWN) {
            // Handle jump
            auto sc = event.key.scancode;
            if ((sc == SDL_SCANCODE_SPACE || sc == SDL_SCANCODE_W || sc == SDL_SCANCODE_UP) && isOnGround) {
                velocityY = jumpForce;
                isOnGround = false;
            }
        }
    }
References handleInput(), isOnGround, and velocityY.
Referenced by handleInput().
if() [1/5]
finalscene::if (bunnyFrames. length, 0)
Definition at line 88 of file finalscene.d.
{
            auto playerTexture = new TextureComponent(bunnyFrames[0]);
            player.AddComponent(ComponentType.TEXTURE, playerTexture);
        }
References player.
if() [2/5]
finalscene::if (frame1 !is null)
References frame1.
if() [3/5]
finalscene::if (frame2 !is null)
References frame2.
if() [4/5]
finalscene::if (frame3 !is null)
References frame3.
if() [5/5]
finalscene::if (frame4 !is null)
References frame4.
render()
override void finalscene::render (SDL_Renderer * renderer)
Definition at line 252 of file finalscene.d.
{
        if (!isActive) return;
        SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
        SDL_RenderClear(renderer);
        // Draw floor (two rows of tiles at bottom of screen)
        if (tileTexture !is null) {
            float tileStartY = 416;
            for (int row = 0; row < 2; row++) {
                for (int i = 0; i < numFloorTiles; i++) {
                    SDL_FRect dest;
                    dest.x = i * tileSize;
                    dest.y = tileStartY + (row * tileSize);
                    dest.w = tileSize;
                    dest.h = tileSize;
                    SDL_RenderTexture(renderer, tileTexture, null, &dest);
                }
            }
        }
        // Draw dead bunny
        if (deadBunnyTexture !is null) {
            SDL_FRect dest;
            dest.x = deadBunnyX;
            dest.y = deadBunnyY;
            dest.w = 32;
            dest.h = 24;
            SDL_RenderTexture(renderer, deadBunnyTexture, null, &dest);
        }
        // Draw player
        if (player !is null) {
            auto transform = player.GetComponent!TransformComponent(ComponentType.TRANSFORM);
            auto textureComp = player.GetComponent!TextureComponent(ComponentType.TEXTURE);
            if (transform !is null && textureComp !is null && textureComp.mTexture !is null) {
                SDL_FRect dest;
                dest.x = transform.rect.x;
                dest.y = transform.rect.y;
                dest.w = transform.rect.w;
                dest.h = transform.rect.h;
                SDL_FlipMode flip = facingLeft ? SDL_FLIP_HORIZONTAL : SDL_FLIP_NONE;
                SDL_RenderTextureRotated(renderer, textureComp.mTexture, null, &dest, 0.0, null, flip);
            }
        }
        // Draw instruction text
        SDL_SetRenderDrawColor(renderer, 200, 200, 200, 255);
        SDL_RenderDebugText(renderer, 180, 50, "Reach your body to return to life!");
        SDL_RenderPresent(renderer);
    }
References deadBunnyTexture, player, render(), tileTexture, and transform.
Referenced by render().
update()
override void finalscene::update ()
Definition at line 116 of file finalscene.d.
{
        if (!isActive) return;
        // Handle horizontal movement
        const bool* keystate = SDL_GetKeyboardState(null);
        float moveX = 0;
        isMoving = false;
        if (keystate[SDL_SCANCODE_LEFT] || keystate[SDL_SCANCODE_A]) {
            moveX = -playerSpeed * deltaTime;
            facingLeft = false;
            isMoving = true;
        }
        if (keystate[SDL_SCANCODE_RIGHT] || keystate[SDL_SCANCODE_D]) {
            moveX = playerSpeed * deltaTime;
            facingLeft = true;
            isMoving = true;
        }
        // Apply horizontal movement
        playerX += moveX;
        // Keep player on screen
        if (playerX < 0) playerX = 0;
        if (playerX > 592) playerX = 592;
        velocityY += gravity * deltaTime;
        playerY += velocityY * deltaTime;
        isOnGround = false;
        // Create player collision rect
        SDL_FRect playerRect;
        playerRect.x = playerX;
        playerRect.y = playerY;
        playerRect.w = 48;
        playerRect.h = 48;
        // Check collision with floor tiles
        float tileStartY = 416;
        for (int row = 0; row < 2; row++) {
            for (int i = 0; i < numFloorTiles; i++) {
                SDL_FRect tileRect;
                tileRect.x = i * tileSize;
                tileRect.y = tileStartY + (row * tileSize);
                tileRect.w = tileSize;
                tileRect.h = tileSize;
                if (SDL_HasRectIntersectionFloat(&playerRect, &tileRect)) {
                    float overlapLeft = (playerX + 48) - tileRect.x;
                    float overlapRight = (tileRect.x + tileRect.w) - playerX;
                    float overlapTop = (playerY + 48) - tileRect.y;
                    float overlapBottom = (tileRect.y + tileRect.h) - playerY;
                    float minOverlap = overlapLeft;
                    int direction = 0;
                    if (overlapRight < minOverlap) {
                        minOverlap = overlapRight;
                        direction = 1;
                    }
                    if (overlapTop < minOverlap) {
                        minOverlap = overlapTop;
                        direction = 2;
                    }
                    if (overlapBottom < minOverlap) {
                        minOverlap = overlapBottom;
                        direction = 3;
                    }
                    if (direction == 0) {
                        playerX = tileRect.x - 48;
                    } else if (direction == 1) {
                        playerX = tileRect.x + tileRect.w;
                    } else if (direction == 2) {
                        playerY = tileRect.y - 48;
                        velocityY = 0;
                        isOnGround = true;
                    } else if (direction == 3) {
                        playerY = tileRect.y + tileRect.h;
                        velocityY = 0;
                    }
                    // Update player rect after correction
                    playerRect.x = playerX;
                    playerRect.y = playerY;
                }
            }
        }
        // Update animation
        if (isMoving) {
            animationTimer += deltaTime;
            if (animationTimer >= frameTime) {
                animationTimer = 0.0f;
                currentFrame = (currentFrame + 1) % cast(int)bunnyFrames.length;
                if (player !is null && bunnyFrames.length > 0) {
                    auto textureComp = player.GetComponent!TextureComponent(ComponentType.TEXTURE);
                    if (textureComp !is null) {
                        textureComp.mTexture = bunnyFrames[currentFrame];
                    }
                }
            }
        } else {
            // Use sitting frame when idle
            if (player !is null && bunnySittingTexture !is null) {
                auto textureComp = player.GetComponent!TextureComponent(ComponentType.TEXTURE);
                if (textureComp !is null) {
                    textureComp.mTexture = bunnySittingTexture;
                }
            }
        }
        // Update player transform
        if (player !is null) {
            auto transform = player.GetComponent!TransformComponent(ComponentType.TRANSFORM);
            if (transform !is null) {
                transform.rect.x = playerX;
                transform.rect.y = playerY;
            }
        }
        // Check if player reached dead bunny
        float distance = (playerX - deadBunnyX) * (playerX - deadBunnyX) +
                        (playerY - deadBunnyY) * (playerY - deadBunnyY);
        if (distance < 50 * 50) {
            writeln("Bunny reunited with its body!");
            if (victoryCallback !is null) {
                victoryCallback();
            }
        }
        sceneTree.update();
    }
References bunnySittingTexture, isOnGround, player, playerX, playerY, transform, update(), velocityY, and writeln().
Referenced by update().
writeln()
finalscene::writeln ("Final Scene initialized!")
References writeln().
Referenced by cleanup(), update(), and writeln().
Variable Documentation
bunnySittingTexture
finalscene::bunnySittingTexture = resourceManager.getTexture("bunny_sitting")
Definition at line 79 of file finalscene.d.
Referenced by update().
deadBunnyTexture
finalscene::deadBunnyTexture = resourceManager.getTexture("bunny_dead")
Definition at line 71 of file finalscene.d.
Referenced by render().
frame1
auto finalscene::frame1 = resourceManager.getTexture("bunny_frame1")
Definition at line 75 of file finalscene.d.
Referenced by if().
frame2
auto finalscene::frame2 = resourceManager.getTexture("bunny_frame2")
Definition at line 76 of file finalscene.d.
Referenced by if().
frame3
auto finalscene::frame3 = resourceManager.getTexture("bunny_frame3")
Definition at line 77 of file finalscene.d.
Referenced by if().
frame4
auto finalscene::frame4 = resourceManager.getTexture("bunny_frame4")
Definition at line 78 of file finalscene.d.
Referenced by if().
isOnGround
finalscene::isOnGround = true
Definition at line 67 of file finalscene.d.
Referenced by handleInput(), and update().
length
bunnyFrames. finalscene::length = 0
Definition at line 74 of file finalscene.d.
player
finalscene::player = new GameObject("Player")
Definition at line 87 of file finalscene.d.
Referenced by AddComponent(), addGameObject(), if(), render(), and update().
playerX
finalscene::playerX = 60
Definition at line 64 of file finalscene.d.
Referenced by update().
playerY
finalscene::playerY = 368
Definition at line 65 of file finalscene.d.
Referenced by update().
tileTexture
finalscene::tileTexture = resourceManager.getTexture("tile")
Definition at line 70 of file finalscene.d.
Referenced by render().
transform
auto finalscene::transform = new TransformComponent(playerX, playerY, 48, 48)
Definition at line 93 of file finalscene.d.
Referenced by AddComponent(), render(), and update().
velocityY
finalscene::velocityY = 0.0f
Definition at line 66 of file finalscene.d.
Referenced by handleInput(), and update().