Lost Bunny: Journey Home: tilemap Namespace Reference
tilemap Namespace Reference
Functions
for (int y=0;y< mapHeight;y++)
void setTile (int mapX, int mapY, int tileIndex)
int getTile (int mapX, int mapY)
void render (int offsetX, int offsetY)
bool screenToMap (int screenX, int screenY, int offsetX, int offsetY, out int mapX, out int mapY)
int getMapWidth ()
int getMapHeight ()
int getTileSize ()
static TileMap loadFromJSON (string filename, TileSet tileset)
void exportAsJSON (string filename)
void exportAsArray (string filename)
Variables
this. mapHeight = mapHeight
this. tileSize = tileSize
this. tileset = tileset
grid = new int[][](mapHeight, mapWidth)
Function Documentation
exportAsArray()
void tilemap::exportAsArray (string filename)
Definition at line 165 of file tilemap.d.
{
        import std.file : write;
        import std.conv : to;
        string output = "// Tilemap data\n";
        output ~= "// Width: " ~ mapWidth.to!string ~ ", Height: " ~ mapHeight.to!string ~ "\n";
        output ~= "int[][] tilemap = [\n";
        for(int y = 0; y < mapHeight; y++) {
            output ~= "    [";
            for(int x = 0; x < mapWidth; x++) {
                output ~= grid[y][x].to!string;
                if(x < mapWidth - 1) output ~= ", ";
            }
            output ~= "]";
            if(y < mapHeight - 1) output ~= ",";
            output ~= "\n";
        }
        output ~= "];\n";
        write(filename, output);
        writeln("Exported tilemap to: ", filename);
    }
References exportAsArray(), grid, and mapHeight.
Referenced by exportAsArray().
exportAsJSON()
void tilemap::exportAsJSON (string filename)
Definition at line 136 of file tilemap.d.
{
        import std.file : write;
        import std.format : format;
        import std.conv : to;
        string json = "{\n";
        json ~= format("  \"width\": %d,\n", mapWidth);
        json ~= format("  \"height\": %d,\n", mapHeight);
        json ~= format("  \"tileSize\": %d,\n", tileSize);
        json ~= "  \"data\": [\n";
        for(int y = 0; y < mapHeight; y++) {
            json ~= "    [";
            for(int x = 0; x < mapWidth; x++) {
                json ~= grid[y][x].to!string;
                if(x < mapWidth - 1) json ~= ", ";
            }
            json ~= "]";
            if(y < mapHeight - 1) json ~= ",";
            json ~= "\n";
        }
        json ~= "  ]\n}";
        write(filename, json);
        writeln("Exported tilemap to: ", filename);
    }
References exportAsJSON(), grid, mapHeight, and tileSize.
Referenced by exportAsJSON().
for()
tilemap::for ()
Definition at line 59 of file tilemap.d.
{
            for(int x = 0; x < mapWidth; x++) {
                grid[y][x] = -1;
            }
        }
References grid, and mapHeight.
getMapHeight()
int tilemap::getMapHeight ()
Definition at line 101 of file tilemap.d.
{ return mapHeight; }
References getMapHeight(), and mapHeight.
Referenced by getMapHeight().
getMapWidth()
int tilemap::getMapWidth ()
Definition at line 100 of file tilemap.d.
{ return mapWidth; }
References getMapWidth().
Referenced by getMapWidth().
getTile()
int tilemap::getTile (int mapX, int mapY)
Definition at line 72 of file tilemap.d.
{
        if(mapX >= 0 && mapX < mapWidth && mapY >= 0 && mapY < mapHeight) {
            return grid[mapY][mapX];
        }
        return -1;
    }
References getTile(), grid, and mapHeight.
Referenced by getTile().
getTileSize()
int tilemap::getTileSize ()
Definition at line 102 of file tilemap.d.
{ return tileSize; }
References getTileSize(), and tileSize.
Referenced by getTileSize().
loadFromJSON()
TileMap tilemap::loadFromJSON (string filename, TileSet tileset) static
Definition at line 105 of file tilemap.d.
{
        import std.file : readText, exists;
        import std.json : parseJSON;
        import std.conv : to;
        if (!exists(filename)) {
            writeln("Error: Tilemap file not found: ", filename);
            return null;
        }
        auto jsonData = readText(filename).parseJSON();
        int width = cast(int)jsonData["width"].integer;
        int height = cast(int)jsonData["height"].integer;
        int tileSize = cast(int)jsonData["tileSize"].integer;
        auto tilemap = new TileMap(width, height, tileSize, tileset);
        auto dataArray = jsonData["data"].array;
        for(int y = 0; y < height && y < dataArray.length; y++) {
            auto row = dataArray[y].array;
            for(int x = 0; x < width && x < row.length; x++) {
                tilemap.setTile(x, y, cast(int)row[x].integer);
            }
        }
        writeln("Loaded tilemap from: ", filename);
        return tilemap;
    }
References loadFromJSON(), and tileSize.
Referenced by loadFromJSON().
render()
void tilemap::render (int offsetX, int offsetY)
Definition at line 79 of file tilemap.d.
{
        for(int y = 0; y < mapHeight; y++) {
            for(int x = 0; x < mapWidth; x++) {
                int tileIndex = grid[y][x];
                if(tileIndex >= 0) { // Render if tile
                    int screenX = offsetX + x * tileSize;
                    int screenY = offsetY + y * tileSize;
                    tileset.renderTile(tileIndex, screenX, screenY);
                }
            }
        }
    }
References grid, mapHeight, render(), and tileSize.
Referenced by render().
screenToMap()
bool tilemap::screenToMap (int screenX, int screenY, int offsetX, int offsetY, out int mapX, out int mapY)
Definition at line 92 of file tilemap.d.
{
        mapX = (screenX - offsetX) / tileSize;
        mapY = (screenY - offsetY) / tileSize;
        return (mapX >= 0 && mapX < mapWidth && mapY >= 0 && mapY < mapHeight);
    }
References mapHeight, screenToMap(), and tileSize.
Referenced by screenToMap().
setTile()
void tilemap::setTile (int mapX, int mapY, int tileIndex)
Definition at line 66 of file tilemap.d.
{
        if(mapX >= 0 && mapX < mapWidth && mapY >= 0 && mapY < mapHeight) {
            grid[mapY][mapX] = tileIndex;
        }
    }
References grid, mapHeight, and setTile().
Referenced by setTile().
Variable Documentation
grid
tilemap::grid = new int[][](mapHeight, mapWidth)
Definition at line 58 of file tilemap.d.
Referenced by exportAsArray(), exportAsJSON(), for(), getTile(), render(), and setTile().
mapHeight
this. tilemap::mapHeight = mapHeight
Definition at line 53 of file tilemap.d.
Referenced by exportAsArray(), exportAsJSON(), for(), getMapHeight(), getTile(), render(), screenToMap(), and setTile().
tileset
this. tilemap::tileset = tileset
Definition at line 55 of file tilemap.d.
tileSize
this. tilemap::tileSize = tileSize
Definition at line 54 of file tilemap.d.
Referenced by exportAsJSON(), getTileSize(), loadFromJSON(), render(), and screenToMap().