Lost Bunny: Journey Home: storyintroscene Namespace Reference
storyintroscene Namespace Reference
Functions
override void cleanup ()
override void handleInput (SDL_Event event)
override void update ()
override void render (SDL_Renderer *renderer)
Variables
waitingForInput = true
framesSinceInit = 0
Function Documentation
cleanup()
override void storyintroscene::cleanup ()
Definition at line 28 of file storyintroscene.d.
{
        writeln("Cleaning up Story Intro Scene...");
    }
References cleanup().
Referenced by cleanup().
handleInput()
override void storyintroscene::handleInput (SDL_Event event)
Definition at line 32 of file storyintroscene.d.
{
        // Only accept input after a few frames to avoid held keys from previous scene
        if (event.type == SDL_EVENT_KEY_DOWN && waitingForInput && framesSinceInit > 5) {
            // Any key starts the game
            if (startGameCallback !is null) {
                startGameCallback();
            }
        }
    }
References framesSinceInit, handleInput(), and waitingForInput.
Referenced by handleInput().
render()
override void storyintroscene::render (SDL_Renderer * renderer)
Definition at line 47 of file storyintroscene.d.
{
        if (!isActive) return;
        SDL_SetRenderDrawColor(renderer, 20, 10, 40, 255);
        SDL_RenderClear(renderer);
        // Draw story text
        drawStoryText(renderer);
        SDL_RenderPresent(renderer);
    }
References render().
Referenced by render().
update()
override void storyintroscene::update ()
Definition at line 42 of file storyintroscene.d.
{
        if (!isActive) return;
        framesSinceInit++; // Increment frame counter
    }
References framesSinceInit, and update().
Referenced by update().
Variable Documentation
framesSinceInit
storyintroscene::framesSinceInit = 0
Definition at line 25 of file storyintroscene.d.
Referenced by handleInput(), and update().
waitingForInput
storyintroscene::waitingForInput = true
Definition at line 24 of file storyintroscene.d.
Referenced by handleInput().