Lost Bunny: Journey Home: tilemap_editor_app Namespace Reference
tilemap_editor_app Namespace Reference
Functions
this ()
void run ()
~this ()
void main ()
Function Documentation
main()
void tilemap_editor_app::main ()
Definition at line 412 of file tilemap_editor_app.d.
            {
    auto editor = new TilemapEditor();
    editor.run();
}
References main().
Referenced by main().
run()
void tilemap_editor_app::run ()
Definition at line 97 of file tilemap_editor_app.d.
               {
        writeln("=== Tilemap Editor - Multi-Level ===");
        writeln("Controls:");
        writeln("  0-8: Select tile type");
        writeln("  Q/W/E: Switch to Level 1/2/3");
        writeln("  Left Click: Place tile");
        writeln("  Right Click: Erase tile");
        writeln("  S: Save ALL levels");
        writeln("  L: Load ALL levels");
        writeln("  C: Clear current level");
        writeln("  ESC: Quit");
        writeln("====================================");
        while (isRunning) {
            handleEvents();
            render();
            SDL_Delay(16);
        }
    }
References run().
Referenced by run().
this()
tilemap_editor_app::this ()
Definition at line 46 of file tilemap_editor_app.d.
           {
        // Create window
        window = SDL_CreateWindow(
            "Tilemap Editor",
            800, 600,
            SDL_WINDOW_RESIZABLE
        );
        if (window is null) {
            writeln("Error: Could not create window");
            return;
        }
        renderer = SDL_CreateRenderer(window, null);
        if (renderer is null) {
            writeln("Error: Could not create renderer");
            return;
        }
        // Initialize all three tilemaps
        tilemaps[0] = new TilemapLevel(gridWidth, gridHeight, tileSize);
        tilemaps[1] = new TilemapLevel(gridWidth, gridHeight, tileSize);
        tilemaps[2] = new TilemapLevel(gridWidth, gridHeight, tileSize);
        // Load textures
        loadTextures();
    }
Referenced by ~this().
~this()
tilemap_editor_app::~this ()
Definition at line 401 of file tilemap_editor_app.d.
            {
        if (tileTexture) SDL_DestroyTexture(tileTexture);
        if (spikeTexture) SDL_DestroyTexture(spikeTexture);
        if (carrotTexture) SDL_DestroyTexture(carrotTexture);
        if (boneTexture) SDL_DestroyTexture(boneTexture);
        if (skullTexture) SDL_DestroyTexture(skullTexture);
        if (renderer) SDL_DestroyRenderer(renderer);
        if (window) SDL_DestroyWindow(window);
    }
References this().