Lost Bunny: Journey Home: gameoverscene Namespace Reference
gameoverscene Namespace Reference
Functions
override void cleanup ()
override void handleInput (SDL_Event event)
override void update ()
override void render (SDL_Renderer *renderer)
Variables
waitingForInput = true
framesSinceInit = 0
Function Documentation
cleanup()
override void gameoverscene::cleanup ()
Definition at line 28 of file gameoverscene.d.
{
        writeln("Cleaning up Game Over Scene...");
    }
References cleanup().
Referenced by cleanup().
handleInput()
override void gameoverscene::handleInput (SDL_Event event)
Definition at line 32 of file gameoverscene.d.
{
        // Only accept input after a few frames to avoid held keys from previous scene
        if (event.type == SDL_EVENT_KEY_DOWN && waitingForInput && framesSinceInit > 5) {
            // Any key returns to menu
            if (returnToMenuCallback !is null) {
                returnToMenuCallback();
            }
        }
    }
References framesSinceInit, handleInput(), and waitingForInput.
Referenced by handleInput().
render()
override void gameoverscene::render (SDL_Renderer * renderer)
Definition at line 47 of file gameoverscene.d.
{
        if (!isActive) return;
        SDL_SetRenderDrawColor(renderer, 40, 0, 0, 255);
        SDL_RenderClear(renderer);
        SDL_SetRenderDrawColor(renderer, 255, 50, 50, 255);
        SDL_RenderDebugText(renderer, 280, 180, "GAME OVER");
        SDL_SetRenderDrawColor(renderer, 200, 200, 200, 255);
        SDL_RenderDebugText(renderer, 190, 300, "Press any key to return to menu");
        SDL_RenderPresent(renderer);
    }
References render().
Referenced by render().
update()
override void gameoverscene::update ()
Definition at line 42 of file gameoverscene.d.
{
        if (!isActive) return;
        framesSinceInit++; // Increment frame counter
    }
References framesSinceInit, and update().
Referenced by update().
Variable Documentation
framesSinceInit
gameoverscene::framesSinceInit = 0
Definition at line 25 of file gameoverscene.d.
Referenced by handleInput(), and update().
waitingForInput
gameoverscene::waitingForInput = true
Definition at line 24 of file gameoverscene.d.
Referenced by handleInput().