Lost Bunny: Journey Home: scenetree Namespace Reference
scenetree Namespace Reference
Data Structures
class SceneTree
class Scene
class SceneManager
Functions
void addChild (SceneNode child)
bool removeChild (SceneNode child)
void update ()
void render (SDL_Renderer *renderer, Camera camera=null)
SceneNode findChild (string childName)
GameObject[] getAllGameObjects ()
Function Documentation
addChild()
void scenetree::addChild (SceneNode child)
Definition at line 23 of file scenetree.d.
{
        if (child is null) return;
        if (child.parent !is null) {
            child.parent.removeChild(child);
        }
        child.parent = this;
        children ~= child;
    }
References addChild().
Referenced by addChild().
findChild()
SceneNode scenetree::findChild (string childName)
Definition at line 70 of file scenetree.d.
{
        foreach (child; children) {
            if (child.name == childName) {
                return child;
            }
            auto found = child.findChild(childName);
            if (found !is null) {
                return found;
            }
        }
        return null;
    }
References findChild().
Referenced by findChild().
getAllGameObjects()
GameObject[] scenetree::getAllGameObjects ()
Definition at line 83 of file scenetree.d.
{
        GameObject[] objects;
        if (gameObject !is null) {
            objects ~= gameObject;
        }
        foreach (child; children) {
            objects ~= child.getAllGameObjects();
        }
        return objects;
    }
References getAllGameObjects().
Referenced by getAllGameObjects().
removeChild()
bool scenetree::removeChild (SceneNode child)
Definition at line 34 of file scenetree.d.
{
        auto index = children.countUntil(child);
        if (index >= 0) {
            child.parent = null;
            children = children.remove(index);
            return true;
        }
        return false;
    }
References removeChild().
Referenced by removeChild().
render()
void scenetree::render (SDL_Renderer * renderer, Camera camera = null)
Definition at line 58 of file scenetree.d.
{
        if (!active) return;
        if (gameObject !is null) {
            gameObject.Render(renderer, camera);
        }
        foreach (child; children) {
            child.render(renderer, camera);
        }
    }
References render().
Referenced by render().
update()
void scenetree::update ()
Definition at line 44 of file scenetree.d.
                  {
        if (!active) return;
        if (gameObject !is null) {
            gameObject.Update();
        }
        // Update all children
        foreach (child; children) {
            child.update();
        }
    }
References update().
Referenced by update().