Lost Bunny: Journey Home: menuscene Namespace Reference
menuscene Namespace Reference
Functions
override void cleanup ()
override void handleInput (SDL_Event event)
override void render (SDL_Renderer *renderer)
Variables
selectedOption = 0
Function Documentation
cleanup()
override void menuscene::cleanup ()
Definition at line 36 of file menuscene.d.
{
        writeln("Cleaning up Menu Scene...");
    }
References cleanup().
Referenced by cleanup().
handleInput()
override void menuscene::handleInput (SDL_Event event)
Definition at line 40 of file menuscene.d.
{
        if (event.type == SDL_EVENT_KEY_DOWN) {
            auto sc = event.key.scancode;
            if (sc == SDL_SCANCODE_UP || sc == SDL_SCANCODE_W) {
                selectedOption = (selectedOption - 1 + 3) % 3;
            }
            else if (sc == SDL_SCANCODE_DOWN || sc == SDL_SCANCODE_S) {
                selectedOption = (selectedOption + 1) % 3;
            }
            else if (sc == SDL_SCANCODE_RETURN || sc == SDL_SCANCODE_SPACE) {
                if (selectedOption == 0 && startGameCallback !is null) {
                    startGameCallback();
                }
                else if (selectedOption == 1 && showCreditsCallback !is null) {
                    showCreditsCallback();
                }
                else if (selectedOption == 2 && quitGameCallback !is null) {
                    quitGameCallback();
                }
            }
        }
    }
References handleInput(), and selectedOption.
Referenced by handleInput().
render()
override void menuscene::render (SDL_Renderer * renderer)
Definition at line 64 of file menuscene.d.
{
        SDL_SetRenderDrawColor(renderer, 30, 20, 50, 255);
        SDL_RenderClear(renderer);
        // Draw background elements
        for (int i = 0; i < 10; i++) {
            SDL_FRect wisp;
            wisp.x = 50 + (i * 60);
            wisp.y = 50 + (i % 3) * 30;
            wisp.w = 20;
            wisp.h = 20;
            SDL_SetRenderDrawColor(renderer, 100, 80, 150, 100);
            SDL_RenderFillRect(renderer, &wisp);
        }
        drawPixelText(renderer, "LOST BUNNY", 140, 60, 6, [200, 150, 255, 255]);
        drawPixelText(renderer, "JOURNEY HOME", 212, 130, 3, [150, 120, 200, 255]);
        drawBunnyIcon(renderer, 320, 200);
        // Draw menu options
        float menuY = 280;
        string[] options = ["START GAME", "CREDITS", "QUIT"];
        for (int i = 0; i < options.length; i++) {
            SDL_FRect optionBox;
            optionBox.x = 200;
            optionBox.y = menuY + (i * 55);
            optionBox.w = 240;
            optionBox.h = 45;
            // Draw option background
            if (i == selectedOption) {
                SDL_SetRenderDrawColor(renderer, 255, 200, 100, 255);
                // Draw selection indicator
                drawArrow(renderer, 170, cast(int)(optionBox.y + 15), true);
                drawArrow(renderer, 455, cast(int)(optionBox.y + 15), false);
            } else {
                SDL_SetRenderDrawColor(renderer, 80, 60, 120, 200);
            }
            SDL_RenderFillRect(renderer, &optionBox);
            // Draw border
            if (i == selectedOption) {
                SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
            } else {
                SDL_SetRenderDrawColor(renderer, 150, 130, 180, 255);
            }
            SDL_RenderRect(renderer, &optionBox);
            // Draw option text
            ubyte[4] textColor = i == selectedOption ? [50, 30, 80, 255] : [220, 200, 255, 255];
            drawPixelText(renderer, options[i], cast(int)optionBox.x + 15, cast(int)optionBox.y + 12, 2, textColor);
        }
        // Draw instructions
        drawPixelText(renderer, "ARROW KEYS TO SELECT", 200, 440, 2, [150, 130, 180, 255]);
        drawPixelText(renderer, "ENTER TO CONFIRM", 224, 460, 2, [150, 130, 180, 255]);
        SDL_RenderPresent(renderer);
    }
References render(), and selectedOption.
Referenced by render().
Variable Documentation
selectedOption
menuscene::selectedOption = 0
Definition at line 33 of file menuscene.d.
Referenced by handleInput(), and render().