Lost Bunny: Journey Home: gameapplication Namespace Reference
gameapplication Namespace Reference
Functions
resManager. loadFromJSON ()
sceneManager. addScene ("menu", menuScene)
sceneManager. addScene ("story", storyScene)
sceneManager. addScene ("gameover", gameOverScene)
sceneManager. addScene ("final", finalScene)
sceneManager. addScene ("victory", victoryScene)
sceneManager. addScene ("credits", creditsScene)
createLevel (1, "assets/tilemaps/lostbunny_level1.json")
createLevel (2, "assets/tilemaps/lostbunny_level2.json")
createLevel (3, "assets/tilemaps/lostbunny_level3.json")
menuScene. setStartGameCallback (() { currentLevel=1;totalCarrotsCollected=0;sceneManager.switchToScene("story");})
menuScene. setShowCreditsCallback (() { sceneManager.switchToScene("credits");})
menuScene. setQuitGameCallback (() { mGameIsRunning=false;})
storyScene. setStartGameCallback (() { sceneManager.switchToScene("level1");})
gameOverScene. setReturnToMenuCallback (() { sceneManager.switchToScene("menu");})
finalScene. setVictoryCallback (() { auto victoryScene=cast(VictoryScene) sceneManager.getScene("victory");if(victoryScene !is null) { victoryScene.setCarrotStats(totalCarrotsCollected, maxCarrotsPossible);} sceneManager.switchToScene("victory");})
sceneManager. switchToScene ("menu")
writeln ("=== Lost Bunny: Journey Home ===")
writeln ("A pet bunny's quest to return from the spirit realm")
writeln ("CPSC 5790 Final Project")
writeln ("\nControls:")
writeln (" Arrow Keys/WASD - Move")
writeln (" T - Talk to spirits (in game)")
writeln (" N - Next level (debug)")
writeln (" ESC - Return to menu")
writeln (" F1 - Menu, F2 - Game")
~this ()
void createLevel (int levelNum, string tilemapFile)
void Input ()
void Update ()
void Render ()
void AdvanceFrame ()
void RunLoop ()
Variables
mRenderer = SDL_CreateRenderer(mWindow, null)
resManager = new ResourceManager(mRenderer)
camera = new Camera(640.0f, 480.0f, 640.0f, 480.0f)
sceneManager = new SceneManager()
auto menuScene = new MenuScene(resManager, camera)
auto storyScene = new StoryIntroScene(resManager, camera)
auto gameOverScene = new GameOverScene(resManager, camera)
auto finalScene = new FinalScene(resManager, camera)
auto victoryScene = new VictoryScene(resManager, camera)
auto creditsScene = new CreditsScene(resManager, camera)
Function Documentation
addScene() [1/6]
sceneManager. gameapplication::addScene ("credits" , creditsScene)
References creditsScene, and sceneManager.
addScene() [2/6]
sceneManager. gameapplication::addScene ("final" , finalScene)
References finalScene, and sceneManager.
addScene() [3/6]
sceneManager. gameapplication::addScene ("gameover" , gameOverScene)
References gameOverScene, and sceneManager.
addScene() [4/6]
sceneManager. gameapplication::addScene ("menu" , menuScene)
References menuScene, and sceneManager.
addScene() [5/6]
sceneManager. gameapplication::addScene ("story" , storyScene)
References sceneManager, and storyScene.
addScene() [6/6]
sceneManager. gameapplication::addScene ("victory" , victoryScene)
References sceneManager, and victoryScene.
AdvanceFrame()
void gameapplication::AdvanceFrame ()
Definition at line 238 of file gameapplication.d.
{
        Input();
        Update();
        Render();
    }
References AdvanceFrame(), Input(), Render(), and Update().
Referenced by AdvanceFrame(), and RunLoop().
createLevel() [1/4]
gameapplication::createLevel (1 , "assets/tilemaps/lostbunny_level1.json")
References createLevel().
Referenced by createLevel(), createLevel(), createLevel(), and createLevel().
createLevel() [2/4]
gameapplication::createLevel (2 , "assets/tilemaps/lostbunny_level2.json")
References createLevel().
createLevel() [3/4]
gameapplication::createLevel (3 , "assets/tilemaps/lostbunny_level3.json")
References createLevel().
createLevel() [4/4]
void gameapplication::createLevel (int levelNum, string tilemapFile)
Definition at line 161 of file gameapplication.d.
{
        auto levelScene = new LostBunnyScene(resManager, camera, levelNum, tilemapFile);
        string sceneName = "level" ~ to!string(levelNum);
        sceneManager.addScene(sceneName, levelScene);
        // Game over callback
        levelScene.setGameOverCallback(() {
            sceneManager.switchToScene("gameover");
        });
        // Return to menu callback
        levelScene.setReturnToMenuCallback(() {
            sceneManager.switchToScene("menu");
        });
        // Next level callback
        levelScene.setNextLevelCallback(() {
            // Get carrot count
            totalCarrotsCollected += levelScene.getCarrotsCollected();
            int nextLevel = levelNum + 1;
            if (nextLevel <= 3) {
                // Continue to next
                currentLevel = nextLevel;
                sceneManager.switchToScene("level" ~ to!string(nextLevel));
            } else {
                // Go to final scene
                sceneManager.switchToScene("final");
            }
        });
    }
References camera, createLevel(), resManager, and sceneManager.
Input()
void gameapplication::Input ()
Definition at line 193 of file gameapplication.d.
                 {
        SDL_Event event;
        while(SDL_PollEvent(&event)) {
            if(event.type == SDL_EVENT_QUIT) {
                mGameIsRunning = false;
            }
            else if(event.type == SDL_EVENT_KEY_DOWN) {
                auto sc = event.key.scancode;
                if(sc == SDL_SCANCODE_F1) {
                    sceneManager.switchToScene("menu");
                }
                else if(sc == SDL_SCANCODE_F2) {
                    sceneManager.switchToScene("level" ~ to!string(currentLevel));
                }
                else {
                    sceneManager.handleInput(event);
                }
            }
            else {
                sceneManager.handleInput(event);
            }
        }
    }
References Input(), and sceneManager.
Referenced by AdvanceFrame(), and Input().
loadFromJSON()
resManager. gameapplication::loadFromJSON ()
References resManager.
Render()
void gameapplication::Render ()
Definition at line 234 of file gameapplication.d.
                  {
        sceneManager.render(mRenderer);
    }
References mRenderer, Render(), and sceneManager.
Referenced by AdvanceFrame(), and Render().
RunLoop()
void gameapplication::RunLoop ()
Definition at line 244 of file gameapplication.d.
                   {
        ulong frames   = 0;
        ulong fps      = 0;
        ulong fpsTimer = SDL_GetTicks();
        lastFrameTime = SDL_GetTicks();
        while (mGameIsRunning) {
            ulong frameStart = SDL_GetTicks();
            deltaTime = (frameStart - lastFrameTime) / 1000.0f;
            lastFrameTime = frameStart;
            if (deltaTime > 1.0f / 30.0f) {
                deltaTime = 1.0f / 60.0f;
            }
            AdvanceFrame();
            frames++;
            if (SDL_GetTicks() - fpsTimer >= 1000) {
                fps = frames;
                frames = 0;
                fpsTimer = SDL_GetTicks();
                string title = "Lost Bunny - FPS: " ~ to!string(fps);
                SDL_SetWindowTitle(mWindow, title.toStringz);
            }
            ulong frameTime = SDL_GetTicks() - frameStart;
            if (frameTime < FRAME_DELAY) {
                SDL_Delay(cast(uint)(FRAME_DELAY - frameTime));
            }
        }
    }
References AdvanceFrame(), and RunLoop().
Referenced by RunLoop().
setQuitGameCallback()
menuScene. gameapplication::setQuitGameCallback (() { mGameIsRunning=false;})
References menuScene.
setReturnToMenuCallback()
creditsScene gameapplication::setReturnToMenuCallback (() { sceneManager.switchToScene("menu");})
References gameOverScene, and sceneManager.
setShowCreditsCallback()
menuScene. gameapplication::setShowCreditsCallback (() { sceneManager.switchToScene("credits");})
References menuScene, and sceneManager.
setStartGameCallback() [1/2]
menuScene. gameapplication::setStartGameCallback (() { currentLevel=1;totalCarrotsCollected=0;sceneManager.switchToScene("story");})
References menuScene, and sceneManager.
setStartGameCallback() [2/2]
storyScene. gameapplication::setStartGameCallback (() { sceneManager.switchToScene("level1");})
References sceneManager, and storyScene.
setVictoryCallback()
finalScene. gameapplication::setVictoryCallback (() { auto victoryScene=cast(VictoryScene) sceneManager.getScene("victory");if(victoryScene !is null) { victoryScene.setCarrotStats(totalCarrotsCollected, maxCarrotsPossible);} sceneManager.switchToScene("victory");})
References finalScene, sceneManager, and victoryScene.
switchToScene()
sceneManager. gameapplication::switchToScene ("menu")
References sceneManager.
Update()
void gameapplication::Update ()
Definition at line 217 of file gameapplication.d.
                  {
        auto currentScene = sceneManager.getCurrentScene();
        if (currentScene !is null) {
            auto bunnyScene = cast(LostBunnyScene)currentScene;
            if (bunnyScene !is null) {
                bunnyScene.setDeltaTime(deltaTime);
            }
            auto finalScene = cast(FinalScene)currentScene;
            if (finalScene !is null) {
                finalScene.setDeltaTime(deltaTime);
            }
        }
        sceneManager.update();
    }
References finalScene, sceneManager, and Update().
Referenced by AdvanceFrame(), and Update().
writeln() [1/9]
gameapplication::writeln (" Arrow Keys/WASD - Move")
References writeln().
writeln() [2/9]
gameapplication::writeln (" ESC - Return to menu")
References writeln().
writeln() [3/9]
gameapplication::writeln (" F1 - Menu, F2 - Game")
References writeln().
writeln() [4/9]
gameapplication::writeln (" N - Next level (debug)")
References writeln().
writeln() [5/9]
gameapplication::writeln (" T - Talk to spirits (in game)")
References writeln().
writeln() [6/9]
gameapplication::writeln ()
References writeln().
Referenced by writeln(), writeln(), writeln(), writeln(), writeln(), writeln(), writeln(), writeln(), and writeln().
writeln() [7/9]
gameapplication::writeln ("\nControls:")
References writeln().
writeln() [8/9]
gameapplication::writeln ("A pet bunny's quest to return from the spirit realm")
References writeln().
writeln() [9/9]
gameapplication::writeln ("CPSC 5790 Final Project")
References writeln().
~this()
gameapplication::~this ()
Definition at line 155 of file gameapplication.d.
            {
        resManager.unloadAll();
        SDL_DestroyRenderer(mRenderer);
        SDL_DestroyWindow(mWindow);
    }
References mRenderer, resManager, and ~this().
Referenced by ~this().
Variable Documentation
camera
gameapplication::camera = new Camera(640.0f, 480.0f, 640.0f, 480.0f)
Definition at line 63 of file gameapplication.d.
Referenced by createLevel().
creditsScene
auto gameapplication::creditsScene = new CreditsScene(resManager, camera)
Definition at line 88 of file gameapplication.d.
Referenced by addScene().
finalScene
auto gameapplication::finalScene = new FinalScene(resManager, camera)
Definition at line 80 of file gameapplication.d.
Referenced by addScene(), setVictoryCallback(), and Update().
gameOverScene
auto gameapplication::gameOverScene = new GameOverScene(resManager, camera)
Definition at line 76 of file gameapplication.d.
Referenced by addScene(), and setReturnToMenuCallback().
menuScene
auto gameapplication::menuScene = new MenuScene(resManager, camera)
Definition at line 68 of file gameapplication.d.
Referenced by addScene(), setQuitGameCallback(), setShowCreditsCallback(), and setStartGameCallback().
mRenderer
gameapplication::mRenderer = SDL_CreateRenderer(mWindow, null)
Definition at line 58 of file gameapplication.d.
Referenced by Render(), and ~this().
resManager
gameapplication::resManager = new ResourceManager(mRenderer)
Definition at line 60 of file gameapplication.d.
Referenced by createLevel(), loadFromJSON(), and ~this().
sceneManager
gameapplication::sceneManager = new SceneManager()
Definition at line 65 of file gameapplication.d.
Referenced by addScene(), addScene(), addScene(), addScene(), addScene(), addScene(), createLevel(), Input(), Render(), setReturnToMenuCallback(), setShowCreditsCallback(), setStartGameCallback(), setStartGameCallback(), setVictoryCallback(), switchToScene(), and Update().
storyScene
auto gameapplication::storyScene = new StoryIntroScene(resManager, camera)
Definition at line 72 of file gameapplication.d.
Referenced by addScene(), and setStartGameCallback().
victoryScene
auto gameapplication::victoryScene = new VictoryScene(resManager, camera)
Definition at line 84 of file gameapplication.d.
Referenced by addScene(), and setVictoryCallback().