Lost Bunny: Journey Home: victoryscene Namespace Reference
victoryscene Namespace Reference
Functions
override void cleanup ()
override void handleInput (SDL_Event event)
override void update ()
override void render (SDL_Renderer *renderer)
Variables
waitingForInput = true
framesSinceInit = 0
Function Documentation
cleanup()
override void victoryscene::cleanup ()
Definition at line 37 of file victoryscene.d.
{
        writeln("Cleaning up Victory Scene...");
    }
References cleanup().
Referenced by cleanup().
handleInput()
override void victoryscene::handleInput (SDL_Event event)
Definition at line 41 of file victoryscene.d.
{
        // Only accept input after a few frames to avoid held keys from previous scene
        if (event.type == SDL_EVENT_KEY_DOWN && waitingForInput && framesSinceInit > 5) {
            // Any key returns to menu
            if (returnToMenuCallback !is null) {
                returnToMenuCallback();
            }
        }
    }
References framesSinceInit, handleInput(), and waitingForInput.
Referenced by handleInput().
render()
override void victoryscene::render (SDL_Renderer * renderer)
Definition at line 56 of file victoryscene.d.
{
        if (!isActive) return;
        SDL_SetRenderDrawColor(renderer, 10, 40, 60, 255);
        SDL_RenderClear(renderer);
        // Draw victory text
        drawVictoryText(renderer);
        SDL_RenderPresent(renderer);
    }
References render().
Referenced by render().
update()
override void victoryscene::update ()
Definition at line 51 of file victoryscene.d.
{
        if (!isActive) return;
        framesSinceInit++; // Increment frame counter
    }
References framesSinceInit, and update().
Referenced by update().
Variable Documentation
framesSinceInit
victoryscene::framesSinceInit = 0
Definition at line 34 of file victoryscene.d.
Referenced by handleInput(), and update().
waitingForInput
victoryscene::waitingForInput = true
Definition at line 33 of file victoryscene.d.
Referenced by handleInput().