Lost Bunny: Journey Home: creditscene Namespace Reference
creditscene Namespace Reference
Functions
override void cleanup ()
override void handleInput (SDL_Event event)
override void render (SDL_Renderer *renderer)
Function Documentation
cleanup()
override void creditscene::cleanup ()
Definition at line 24 of file creditscene.d.
{
        writeln("Cleaning up Credits Scene...");
    }
References cleanup().
Referenced by cleanup().
handleInput()
override void creditscene::handleInput (SDL_Event event)
Definition at line 28 of file creditscene.d.
{
        if (event.type == SDL_EVENT_KEY_DOWN) {
            // Any key press returns to menu
            if (returnToMenuCallback !is null) {
                writeln("Returning to menu from credits...");
                returnToMenuCallback();
            }
        }
    }
References handleInput().
Referenced by handleInput().
render()
override void creditscene::render (SDL_Renderer * renderer)
Definition at line 38 of file creditscene.d.
{
        SDL_SetRenderDrawColor(renderer, 30, 20, 50, 255);
        SDL_RenderClear(renderer);
        for (int i = 0; i < 10; i++) {
            SDL_FRect wisp;
            wisp.x = 50 + (i * 60);
            wisp.y = 50 + (i % 3) * 30;
            wisp.w = 20;
            wisp.h = 20;
            SDL_SetRenderDrawColor(renderer, 100, 80, 150, 100);
            SDL_RenderFillRect(renderer, &wisp);
        }
        drawPixelText(renderer, "CREDITS", 215, 60, 5, [200, 150, 255, 255]);
        drawPixelText(renderer, "LOST BUNNY", 200, 130, 4, [150, 120, 200, 255]);
        drawPixelText(renderer, "JOURNEY HOME", 212, 170, 3, [120, 100, 170, 255]);
        drawPixelText(renderer, "CREATED BY", 230, 220, 3, [180, 160, 220, 255]);
        drawPixelText(renderer, "NOAH SAFAR", 230, 260, 3, [220, 200, 255, 255]);
        drawPixelText(renderer, "CELESTE VAN DOKKUM", 158, 295, 3, [220, 200, 255, 255]);
        drawPixelText(renderer, "CPSC 5790", 239, 345, 3, [150, 130, 200, 255]);
        drawPixelText(renderer, "FINAL PROJECT", 203, 380, 3, [150, 130, 200, 255]);
        drawPixelText(renderer, "PRESS ANY KEY TO RETURN", 182, 450, 2, [150, 130, 180, 255]);
        SDL_RenderPresent(renderer);
    }
References render().
Referenced by render().