Lost Bunny: Journey Home: component_system Namespace Reference
component_system Namespace Reference
Data Structures
class Camera
Camera class for world-to-screen coordinate transformation.
interface IComponent
class TransformComponent
class TextureComponent
class ScriptComponent
class GameObject
class PlayerScript
class AlienScript
class ProjectileScript
class DirectionalProjectileScript
class AsteroidScript
class AnimationComponent
Enumerations
enum ComponentType {
TRANSFORM , TEXTURE , ANIMATION , COLLIDER ,
SCRIPT
}
Functions
SDL_FRect makeRect (float x, float y, float w, float h)
GameObject CreatePlayer (ResourceManager res)
GameObject CreateEnemy (ResourceManager res, float x, float y)
GameObject CreateProjectile (ResourceManager res, float startX, float startY, float speed, string bmpPath="bullet")
GameObject CreateDirectionalProjectile (ResourceManager res, float startX, float startY, float speed, float angle, string bmpPath="bullet")
GameObject CreateAsteroid (ResourceManager res, float startX, float startY, float velX, float velY, float rotSpeed, float size=60.0f)
Variables
__gshared float g_deltaTime = 0.0f
Global deltaTime for frame-independent movement.
Enumeration Type Documentation
ComponentType
enum component_system::ComponentType
Enumerator
TRANSFORM
TEXTURE
ANIMATION
COLLIDER
SCRIPT
Definition at line 115 of file component_system.d.
{ TRANSFORM, TEXTURE, ANIMATION, COLLIDER, SCRIPT }
Function Documentation
CreateAsteroid()
GameObject component_system::CreateAsteroid (ResourceManager res, float startX, float startY, float velX, float velY, float rotSpeed, float size = 60.0f)
Definition at line 589 of file component_system.d.
{
    auto go = new GameObject("Asteroid");
    auto xf = new TransformComponent(startX, startY, size, size);
    go.AddComponent(ComponentType.TRANSFORM, xf);
    auto tex = new TextureComponent(res.getTexture("enemy"));
    go.AddComponent(ComponentType.TEXTURE, tex);
    go.AddScript(new AsteroidScript(velX, velY, rotSpeed));
    return go;
}
References CreateAsteroid().
Referenced by CreateAsteroid().
CreateDirectionalProjectile()
GameObject component_system::CreateDirectionalProjectile (ResourceManager res, float startX, float startY, float speed, float angle, string bmpPath = "bullet")
Definition at line 577 of file component_system.d.
{
    auto go = new GameObject("DirectionalProjectile");
    auto xf = new TransformComponent(startX - 4, startY - 16, 16, 32);
    go.AddComponent(ComponentType.TRANSFORM, xf);
    auto tex = new TextureComponent(res.getTexture(bmpPath));
    go.AddComponent(ComponentType.TEXTURE, tex);
    go.AddScript(new DirectionalProjectileScript(speed, angle));
    return go;
}
References CreateDirectionalProjectile().
Referenced by CreateDirectionalProjectile(), and component_system::PlayerScript::OnUpdate().
CreateEnemy()
GameObject component_system::CreateEnemy (ResourceManager res, float x, float y)
Definition at line 553 of file component_system.d.
{
    auto go = new GameObject("Enemy");
    auto xf = new TransformComponent(x, y, 60, 60);
    go.AddComponent(ComponentType.TRANSFORM, xf);
    auto tex = new TextureComponent(res.getTexture("enemy"));
    go.AddComponent(ComponentType.TEXTURE, tex);
    go.AddScript(new AlienScript(res));
    return go;
}
References CreateEnemy().
Referenced by CreateEnemy().
CreatePlayer()
GameObject component_system::CreatePlayer (ResourceManager res)
Definition at line 536 of file component_system.d.
{
    auto go = new GameObject("Player");
    auto xf = new TransformComponent((1280/2) - 25, (960/2) - 25, 50, 50);
    go.AddComponent(ComponentType.TRANSFORM, xf);
    // ResourceManager for texture
    auto tex = new TextureComponent(res.getTexture("spritesheet"));
    go.AddComponent(ComponentType.TEXTURE, tex);
    // Animation component
    auto anim = new AnimationComponent(res.getAnimationPath("spritesheet"));
    go.AddComponent(ComponentType.ANIMATION, anim);
    go.AddScript(new PlayerScript(res));
    return go;
}
References CreatePlayer().
Referenced by CreatePlayer().
CreateProjectile()
GameObject component_system::CreateProjectile (ResourceManager res, float startX, float startY, float speed, string bmpPath = "bullet")
Definition at line 565 of file component_system.d.
{
    auto go = new GameObject("Projectile");
    auto xf = new TransformComponent(startX - 4, startY, 16, 32);
    go.AddComponent(ComponentType.TRANSFORM, xf);
    auto tex = new TextureComponent(res.getTexture(bmpPath));
    go.AddComponent(ComponentType.TEXTURE, tex);
    go.AddScript(new ProjectileScript(speed));
    return go;
}
References CreateProjectile().
Referenced by CreateProjectile(), and component_system::AlienScript::OnUpdate().
makeRect()
SDL_FRect component_system::makeRect (float x, float y, float w, float h)
Definition at line 534 of file component_system.d.
{ SDL_FRect r; r.x = x; r.y = y; r.w = w; r.h = h; return r; }
References makeRect().
Referenced by makeRect().
Variable Documentation
g_deltaTime
__gshared float component_system::g_deltaTime = 0.0f
Global deltaTime for frame-independent movement.
Definition at line 29 of file component_system.d.
Referenced by component_system::AlienScript::OnUpdate(), component_system::AsteroidScript::OnUpdate(), component_system::DirectionalProjectileScript::OnUpdate(), component_system::PlayerScript::OnUpdate(), and component_system::ProjectileScript::OnUpdate().